### PR TITLE
Implement --cc and --cxx flags for overriding compiler detection

### PR DESCRIPTION
**Pull request by ColdenCullen**
Some newer versions of clang install as clang-9 & clang++-9 to allow side-by-side installs. This allows the user to explicitly specify which compiler they'd like to use instead of hard-coding acceptable binary names.

### CODE REVIEW

**Comment by ColdenCullen** [comment]
@unbornchikken can I get a review on this please?

**Comment by unbornchikken** [comment]
Please update readme.md according to the new help screen that your version provides.

**Comment by ColdenCullen** [comment]
Done!

**Comment by unbornchikken** [comment]
Many thanks. Gonna put a new tag soon.

**Comment by ColdenCullen** [comment]
Perfect, thank you!

**Pull request merged**
