### PR TITLE
Adjust 7.X to support NodeJS 10+ as minimum version

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
This PR introduces changes needed to allow 7.X to work with NodeJS version 10+, dropping the minimum requirement from NodeJS 14+ to NodeJS 10+.

This PR will allow users using NodeJS 10 to update from 6.X to 7.X, closing #292. I work on the [AWS IoT SDK for Javascript V2](https://github.com/aws/aws-iot-device-sdk-js-v2) and unfortunately we cannot update from 6.X to 7.X easily because our minimum NodeJS version is 10.13+, and so we cannot fix the vulnerability reported in #292 by upgrading the version of CMakeJS we use.
(*It's only a built-time issue for us and we control the input going to it, therefore has no direct security impact in our case. We still get security reports on it though and therefore ideally would like to fix it if possible.*)

To add NodeJS 10+ support to 7.X, this PR makes the following changes:
* Adjusts the code to not rely on any NodeJS features beyond NodeJS 10.
  * The biggest change is removing the use of `require("module").createRequire` since it's a NodeJS 12 feature and replacing it with getting the include directory from `require("node-addon-api").include` directly.
* Adjusts packages to the latest versions that support NodeJS 10. Packages impacted are:
  * `axios` -> `^1.3.2` to `^0.27.2`
  * `yargs` -> `^17.6.0` to `^16.2.0`
  * `mocha` -> latest (`*`) to `^9.2.2`
  * `node-addon-api` -> `^6.0.0` to `^3.2.1`
* Adds NodeJS 10 tests to CI alongside the existing NodeJS 14 tests
* Adjusts README documentation to mention NodeJS 10 as the minimum supported version.

All changes were tested with the test suite in CMakeJS on both NodeJS 14 and NodeJS 10 and all tests are passing. I also tested building the [AWS IoT CRT for Javascript](https://github.com/awslabs/aws-crt-nodejs) and the [AWS IoT SDK for Javascript](https://github.com/aws/aws-iot-device-sdk-js-v2) on MacOS and confirmed both worked as expected with these changes.

_____________

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Julusian** [comment]
Sorry, I have been busy on other things and this slipped through the cracks.
I am open to this, but at the same time I don't want to end up being burdened with supporting nodejs 10 for many years unless it is necessary to. Although that aws stuff does look like it is the biggest consumer of cmake-js, it would make sense to match what you need.

Since this was opened, it looks like the required nodejs versions for [the aws-crt is being changed to 14 'soonish'](https://github.com/awslabs/aws-crt-nodejs/discussions/468). So I am wondering if it is still beneficial to do this pr as well

**Comment by TwistedTwigleg** [comment]
Hi @Julusian,

Not a problem. I actually no longer work for AWS, but I made this PR for the Javascript CRT while I was on the AWS IoT SDK team. I’m not sure if this is still necessary or not.

@bretambrose @graebm - do either of you know if this PR is still needed or not given the possibility of a move to Node 14?

**Comment by bretambrose** [comment]
I think we can drop this.  Will  wait a little longer for any feedback and then jump to 14 and cmake-js 7.x in late August if nothing comes up.

**Comment by TwistedTwigleg** [comment]
Okay, cool. I’ll leave it open for now then. Once you guys confirm your good to jump let me know and, if there isn’t a need for it, I’ll close the PR.

**Comment by TwistedTwigleg** [comment]
Looking at the CRT repository, it looks like the plan is still to move to a newer version of NodeJS, in which case this PR will not be needed. Going to close this so it isn't cluttering up the CmakeJS repository.

**Pull request closed without merging**
