### PR TITLE
Custom configure options

### PR DESCRIPTION
**Pull request by gerhardberger**
Hi!

I'm using `cmake-js` from code and I needed to pass in options for configuration, so I added this options to the configure and build commands.

### CODE REVIEW

**Comment by unbornchikken** [comment]
There is already an option system exists in this library, you can pass options to worker classes in their constructor. It would be much better if you use that like by having something like this:

```js
let opts = {
 cMakeOptions: {
  foo: "bar"
 }
};

var buildSystem = new BuildSystem(opts);
buildSystem.compile();
```

Because if we use this already existing option passing infrastructure, then it would be very easy to integrate this feature in to the binary to have something like this in the commandline:

```
cmake-js -CDfoo="bar" -CDklow="mudz yemm-yemm"
```

Where "C" prefix means an argument to be passed to CMake.

What do you say?

**Comment by gerhardberger** [comment]
Sounds good to me!

I create a `BuildSystem` at the beginning of my code and then in different functions I configure, build or rebuild, that's why I implemented this way, but it doesn't change much this way I just need to create a `BuildSystem` in each function, but overall it's the same. And it's cleaner this way.

I'll send the new PR later!

**Comment by gerhardberger** [comment]
hi, I commited the reworked version. hopefully it's all good!

**Comment by unbornchikken** [comment]
LGTM

**Comment by unbornchikken** [comment]
Released in 3.1. Thanks!

**Pull request merged**
