### PR TITLE
VS2017 build tools detection fix (es6)

### PR DESCRIPTION
**Pull request by diegoperini**
I used the newly suggested [vswhere](https://github.com/Microsoft/vswhere) method to detect VS installations. I copied the `vswhere.exe` from my own VS2017 installation. That can be replaced with a fresh copy by maintainers for security purposes.

This pull request only fixes the es6 implementation. Modifications for es5 is still necessary.

### CODE REVIEW

**Comment by diegoperini** [comment]
Will do with added es5 support late today. Thanks for the suggestions.

**Comment by unbornchikken** [comment]
ES5 code gets generated automatically, you should only work on the ES6 side of things.

**Comment by diegoperini** [comment]
Oh, good to hear that.

**Comment by diegoperini** [comment]
I think this time it is appropriate.

**Comment by unbornchikken** [comment]
Ty. Gonna release this soon.

**Comment by diegoperini** [comment]
Happy to help. :)

**Pull request merged**
