### PR TITLE
Fixed auto generator selection on windows

### LINKED ISSUE #168: ERR! OMG There is no Visual C++ compiler installed. Install Visual C++ Build Toolset or Visual Studio.
Hi Everyone,

I run cmake on npm but I get a this error(below). I have installed Visual Studio 2019 Community Edition. 

How can I figure out this error?

cmake_Error

### PR DESCRIPTION
**Pull request by nik-m2**
Fixes #168 

Credit to @BurningEnlightenment for the `vswhere` command execution code.

This PR takes the approach of ignoring the "C++ Build Tools" Visual Studio workload during the `cmake-js` dependency check stage.

To include a message, warning users they don't have the dependency one of the following could be done:

- Add another check after getting the windows generator, and make sure that the generator version has the C++ build tools installed
- Add output to failed project generation indicating they may be missing the package.
  - E.g "Could not generate project. Are Visual Studio C++ tools and CMake 3.14+ installed?"
  -  This is the approach I took with my small no-configuration generate + build scripts and always promptly reminded me

### CODE REVIEW

**Comment by BurningEnlightenment** [comment]
@nik-m2 thanks, for doing the work! In principle this is a much better and thorough solution than the quick fix proposed in #171 (will close it if this gets merged).
Using vswhere to drive the version selection process also eliminates the currently buggy behavior to not always selecting the newest available VS version. Nevertheless, checking whether CMake supports the selected version seems like a good idea.

However, ignoring the VC++ Build Tools Workload would be a showstopper for me, because none of the nodejs only developers in my Team need nor want a full Visual Studio installation which is also the case for (transitive) package consumers and CI environments. Furthermore this would make the cursed but widely used [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) unusable with cmake-js.
@nik-m2 Did you encounter any technical obstacles which led to the exclusion? Would you mind me adding support for said workload?

**Comment by nik-m2** [comment]
@BurningEnlightenment No problem! I'm glad you like my solution.

That's great to know I don't need the full Visual Studio version, I have only testing a few work flows. Do you know if `windows-build-tools` will still work with, and won't break a normal Visual Studio installation?

I didn't run into any technical problems, just haven't used it before. I mentioned it in case it would be a problem, so go ahead by all means!

**Comment by unbornchikken** [comment]
It got kinda complicated in the end. Please help me on verify this. If you have a complete VS or just build tools installation at hand tell us the results there.

**Comment by nik-m2** [comment]
@unbornchikken With what I currently have I am able to detect a full installation only. I added detecting `windows-build-tools` as an attempt to give better support. I have tried with a partial installation but I'm not certain that I will be able to create a typical use case as I haven't used a partial VS installation

**Pull request closed without merging**
